name: Run Tests

# Controls when the workflow will run
on: 
  push:
  pull_request:
    branches: 
      - '**:**'  # Only run for pull requests submitted from forks

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Load Modules
        run: |
          module purge
          module load bats

      - uses: actions/checkout@v2

      - name: Run tests
        run: ./run_tests.sh
        shell: bash
        env:
          CRC_BANK_DB: ./test.db
          CRC_TEST: true
