name: Run Tests

# Controls when the workflow will run
on: 
  push:
  pull_request:
    branches: 
      - '**:**'  # Only run for pull requests submitted from forks

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    # Set default shell options for all run steps
    defaults:
      run:
        shell: bash -leo pipefail {0}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Run tests
        run: |
          module purge
          module load bats python/3.7.0
          module list
          ./run_tests.sh
        env:
          CRC_BANK_TEST: true
